#!/bin/bash
#
# CourseShark run file
#
#

# Make sure the environment vars are loaded
. ~/.env_vars

# Install requirements
npm install

if [ "development" == "$NODE_ENV" ]
then
  echo "";
  echo "Starting :: $(tput setaf 4)Dev Environment";
  echo "$(tput setaf 2)  * nodemon watching scripts";
  echo "  * no node version check (running $(tput sgr0)$(tput setaf 3)$(node -v;)$(tput setaf 2))";
  echo "";
  nodemon ./app.js;
  exit;
else
  if [ "admin" == "$COURSESHARK_MODE" ]
  then
    # Start up the admin server
    node ./admin.js
  elif [ "seat-watcher" == "$COURSESHARK_MODE" ]
  then
    # Start in seatwatcher mode
    node ./seat-watcher.js
  else
    # Start the app in normal mode
    node ./app.js
  fi
fi
